## Application Name
spring.application.name=module3

## Server connection properties
server.address=127.0.0.1
server.port=8443

## SSL / HTTPS Configuration
server.ssl.enabled=true
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
